spring.application.name=API-Gateway
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Gateway + Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
#spring.cloud.gateway.routes[0].id=currency-exchange
#spring.cloud.gateway.routes[0].uri=http://localhost:8000
#spring.cloud.gateway.routes[0].predicates[0]=Path=/currency-exchange/**
logging.level.org.springframework.cloud.gateway=DEBUG
